### ISSUE TITLE
Cannot request access to APIs in other orgs

### ISSUE THREAD

**Issue by dennypc** [kloudtek/anypoint-tools#10]
Hi! We're running into an issue while creating a client application, saying that the "other API" is not found.  We believe the root cause of the issue is that the "Other API" is on another Organization and that the API list being checked during the provisioning process is tied to an org.  We're able to manually add clients since the deploy user has access to APIs across all organizations. 

Thanks so much for your help in resolving this 👍

**Comment by ymenager** [comment]
fixed in master branch
