### ISSUE TITLE
API Provisioning cannot find API Spec

### ISSUE THREAD

**Issue by strangr525** [kloudtek/anypoint-tools#16]
The offset value in https://anypoint.mulesoft.com/apimanager/xapi/v1/organizations/f31b2b20-fdd0-4fe4-a5e2-2cb90d69c05d/apiSpecs?ascending=true&limit=50&offset=50&searchTerm=acme

needs to be set to '0' and not '50'.

**Comment by ymenager** [comment]
the offset is not hardcoded, it will paginate through each page starting at 0. That code is shared for all paginations:

```
public abstract class PaginatedList<X, Z extends AnypointObject> implements Iterable<X> {
    protected Z parent;
    protected int limit = 100;
    protected int offset = 0;
    protected int total = -1;
```
